### ISSUE TITLE
Reduce number of install phases, but split them into smaller functions

### ISSUE THREAD

**Issue by m1kola** [Azure/ARO-RP#106]
Currently we have 3 install phases and functions that implement these phases are big:

https://github.com/Azure/ARO-RP/blob/45142afd5451ddc534427e29fdccf0ba4bb2a360/pkg/install/install.go#L110-L132

Would be great to reduce the number of install phases to two:
* everything before we delete the bootstrap
* bootstrap deletion and everything after

But at the same time move every step of the process into a separate, testable function.

So we will be able to extend and more easily unit test the installation process, but at the same time keep two major phases separate.

Background: https://github.com/Azure/ARO-RP/pull/85#discussion_r369881481

**Comment by jim-minter** [comment]
@nilsanderselde please can you take this on as a priority?

**Comment by nilsanderselde** [comment]
Regroup steps into two phases: https://github.com/Azure/ARO-RP/pull/253

**Comment by nilsanderselde** [comment]
There could possibly be further refactoring done to the larger install steps like ARM template deployments, but I think this issue has been largely resolved by the following PRs (listed in the order they were merged):
1. https://github.com/Azure/ARO-RP/pull/196
2. https://github.com/Azure/ARO-RP/pull/211
3. https://github.com/Azure/ARO-RP/pull/201
4. https://github.com/Azure/ARO-RP/pull/304
5. https://github.com/Azure/ARO-RP/pull/316
6. https://github.com/Azure/ARO-RP/pull/380
