### ISSUE TITLE
az aro create failed

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#114]
`az aro create` failed with fresh vnet:
```
This command group is in preview. It may be changed/removed in a future release.
Deployment failed. Correlation ID: bf750d65-99ae-4945-8327-298dc79fed44. Internal server error.
```

Second error:
```
Subnet GatewaySubnet is in use by /subscriptions/225e02bc-43d0-43d1-a01a-17e584a4ef69/resourceGroups/v4-eastus/providers/Microsoft.Network/virtualNetworkGateways/dev-vpn/ipConfigurations/default and cannot be deleted. In order to delete t
he subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.  
```

My assumption is that when using `az aro create` we should add required role binding to the resources. But as we already know RBAC sometimes lags to propagate due to caching via different RP despite the fact it returns `200`. This makes the first create obscure and random failure.

**Comment by mjudeikis** [comment]
Related: https://github.com/Azure/ARO-RP/issues/66 
Related: https://github.com/Azure/ARO-RP/issues/93

**Comment by jim-minter** [comment]
I checked the RP logs, the deployment failure is #66.
What did you do to get the second error - did you try to delete the whole vnet, or the GatewaySubnet?

**Comment by jim-minter** [comment]
Removing labels because if there is a new issue to be dealt with here, I don't think it's understood yet.

**Comment by mjudeikis** [comment]
I deleted it, recreated new one and tried the same
