### ISSUE TITLE
HashConflictOnDifferentRoleAssignmentIds - e2e production failure

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#1175]
time="2020-11-18T01:47:27Z" level=info msg=BeforeSuite func="e2e.glob..func14()" file="test/e2e/setup.go:186"
time="2020-11-18T01:47:27Z" level=info msg="running in production mode" func="e2e.setup()" file="test/e2e/setup.go:131"
time="2020-11-18T01:47:27Z" level=info msg="creating AAD application" func="cluster.(*Cluster).Create()" file="pkg/util/cluster/cluster.go:125"
time="2020-11-18T01:47:28Z" level=info msg="creating resource group" func="cluster.(*Cluster).Create()" file="pkg/util/cluster/cluster.go:137"
time="2020-11-18T01:47:31Z" level=info msg="predeploying ARM template" func="cluster.(*Cluster).Create()" file="pkg/util/cluster/cluster.go:169"
Panic [64.247 seconds]
[BeforeSuite] BeforeSuite 
/home/cloud-user/agent/_work/4/go/src/github.com/Azure/ARO-RP/test/e2e/setup.go:185

  Test Panicked
  Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"HashConflictOnDifferentRoleAssignmentIds\",\r\n    \"message\": \"A hash conflict was encountered for the role Assignment ID. Please use a new Guid.\"\r\n  }\r\n}"}]
  /home/cloud-user/agent/_work/4/go/src/github.com/Azure/ARO-RP/test/e2e/setup.go:192

Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"HashConflictOnDifferentRoleAssignmentIds\",\r\n    \"message\": \"A hash conflict was encountered for the role Assignment ID. Please use a new Guid.\"\r\n  }\r\n}"}]

**Comment by mjudeikis** [comment]
https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=36848191&view=logs&j=7f927075-9eaf-5028-a98e-50e4f06c0a5d&t=5118498b-ca6b-5ead-df15-d7dc83d82d1c

**Comment by jim-minter** [comment]
fixed

**Comment by jeevanbalanmanoj** [comment]
We are seeing a similar question, any leads will be helpful https://stackoverflow.microsoft.com/questions/244334 @mjudeikis  @jim-minter
