### ISSUE TITLE
How to encrypt ARO nodes with custom key like AKS 

### ISSUE THREAD

**Issue by saswatmohanty01** [Azure/ARO-RP#1223]
I am trying to find a way to encrypt openshift nodes running in Azure using customer managed key . Same feature is supported in AKS while creating clusters. Please provide any documents from Azure or Redhat . 

Thanks

**Comment by mjudeikis** [comment]
@saswatmohanty01 this is on the roadmap and coming. We are in the process of enabling Openshift to do this, and once this is done ARO will follow soon after.
