### ISSUE TITLE
PE/PLS deletion failure when cluster RG is deleted by customer

### ISSUE THREAD

**Issue by julienstroheker** [Azure/ARO-RP#152]
When a customer will delete the cluster resource group (aro-xxxxxx) manually via CLI/Portal, PLS deletion will fail because PE will still exist. 

I guess there is no clean way to handle this, customer should trigger a DELETE operation using the RP.

**Comment by jim-minter** [comment]
I wonder if it's an argument to entirely prevent the customer from deleting the cluster RG.  Does the RP delete succeed after the customer tried to delete the cluster RG?

**Comment by julienstroheker** [comment]
will validate this.

**Comment by kwoodson** [comment]
I have experienced this on v3 as well.  When calling a delete through the fake rp in v3 it was successful.  The manual steps to remove were to remove each of the private endpoints which then allowed the resource group to be deleted.

**Comment by jim-minter** [comment]
I believe this is no longer an issue now that denyAssignments have merged, closing.
