### ISSUE TITLE
Makefile assumes python version

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/ARO-RP#159]
From `https://github.com/Azure/ARO-RP/blob/master/docs/using-az-aro.md`, it references `make az` which runs:
https://github.com/Azure/ARO-RP/blob/master/Makefile#L8

which assumes python point to python3; however, the Azure Ubuntu 18 image still uses python2 as the default version.  I recommend using python3.

**Comment by jim-minter** [comment]
At the moment `az` supports python 2 and python 3. We aim to do the same, and our CI tests both paths, so we don't hard code this. One way to set this as an end user is to use a python virtualenv.

**Comment by lastcoolnameleft** [comment]
I'm no longer with the user that reported the issue; however, there was definitely an issue using it on a brand new VM which defaulted to Python 2.  I'm spitballing here, but I think "setuptools" was not found.  Perhaps a requirements file might assist.  If I encounter the error again, I'll post here.

**Comment by jim-minter** [comment]
Please.  I'm pretty sure we're missing an optional line in the docs about installing setuptools, but I don't know the details of what is needed.  If you can find out, we'll add it to the docs.

**Comment by ehashman** [comment]
> I'm spitballing here, but I think "setuptools" was not found.

The distro setuptools are likely way out of date and should be upgraded (e.g. `pip install -U setuptools`). Even if the user got beyond that step, make would probably fail on the wheel building because the wheel package isn't installed by default. If I hit this I'll try to fix either the docs or script.

**Comment by jim-minter** [comment]
closing as stale
