### ISSUE TITLE
Standardize creation of dynamichelper.Interface in pkg/operator

### ISSUE THREAD

**Issue by nilsanderselde** [Azure/ARO-RP#1608]
Most of the controllers in the ARO operator that use `dynamichelper.Interface` use one that is passed in from `cmd/aro/operator.go`.

However, there are a couple places where `dh` is created later:
- [pkg/operator/controllers/genevalogging/genevalogging_controller.go in `Reconcile` function](https://github.com/Azure/ARO-RP/blob/e4ff2a4328ccf77aa600d332364ae8fd4f7b28d9/pkg/operator/controllers/genevalogging/genevalogging_controller.go#L65-L72), with comment that it "currently saves us in the case that the controller runs before the SCC API is registered."
- [pkg/operator/controllers/routefix/routefix_controller.go in `deploy` function](https://github.com/Azure/ARO-RP/blob/e4ff2a4328ccf77aa600d332364ae8fd4f7b28d9/pkg/operator/controllers/routefix/routefix_controller.go#L86-L93), with comment that it "currently saves us in the case that the controller runs before the SCC API is registered."
- [pkg/operator/controllers/workaround/workaround_controller.go in `NewReconciler` function](https://github.com/Azure/ARO-RP/blob/master/pkg/operator/controllers/workaround/workaround_controller.go#L38-L41). No comment indicating why.

In these places, if we ever really had to create `dh` later (might have been copy/paste or just inconsistency), do we still have to?

Or, conversely, should we always create `dh` at the lowest scope possible?

**Comment by ArielLima** [comment]
Issue was resolved with this PR: https://github.com/Azure/ARO-RP/pull/1602
