### ISSUE TITLE
Remove from NSG e2e test turning on operator NSG reconciliation after we default to being on 

### ISSUE THREAD

**Issue by ross-bryan** [Azure/ARO-RP#1735]
Currently e2e does some checks to turn it on. Once we default it to on we can remove that code.

Original PR https://github.com/Azure/ARO-RP/pull/1660

**Comment by ArielLima** [comment]
@bryanro92 can we close this issue?

**Comment by ross-bryan** [comment]
yes, lets close this issue @ArielLima
