### ISSUE TITLE
Cluster creation phase not rerunable

### ISSUE THREAD

**Issue by Makdaam** [Azure/ARO-RP#175]
Replication steps: create a cluster, wait for "waiting for bootstrap configmap" step in logs, kill the RP, start and register a new RP which should pick up the process. It failes during ARM deployment.

The issue is to investigate, find the cause and make ARM idempotent.

The ARM deployment fails on LoadBalancer creation if the cluster creation is restarted after "waiting for bootstrap configmap" step. There seems to be a conflict in forwarding rules.

**Comment by jim-minter** [comment]
fixed in #185
