### ISSUE TITLE
Increase fault tolerance of installer

### ISSUE THREAD

**Issue by nilsanderselde** [Azure/ARO-RP#229]
Rather than just returning errors which occur in the `install` package to the backend `try` function and logging them, try to recover from them here: https://github.com/Azure/ARO-RP/pull/201/files#diff-90259a58ac8d65a2b486198e4eebb9c3R182-R197.

**Comment by jim-minter** [comment]
is there actually anything to be done here @nilsanderselde ?

**Comment by nilsanderselde** [comment]
@jim-minter I'll take a look today.

**Comment by nilsanderselde** [comment]
I think there may be some common errors which occur from specific install steps for which a retry might save time, preventing us from needing to restart the entire phase. As the installation can take a while, identifying those common errors and retrying at the step level might be worth it. My concern is it might be a little to brittle to deal with specific errors from specific steps here. I suppose a new function could be written which checks 1. which step the installer is on and 2. which error was returned and then retries it - I'm not sure what else there would be to do other than retry.

I think the scope of this issue may be too broad. If we run into chronic problems with certain steps in the future, we could consider adding logic here to deal with it, but I'll close this for now.
