### ISSUE TITLE
e2e succeeding when it should be failing

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#246]
The following run should have errored out, but it didn't

https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=29216165&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=cc311011-c8c8-5cb4-274c-19f32b3aecb1

**Comment by jim-minter** [comment]
@julienstroheker please can you take a look?  I'm conscious that I don't want to adversely affect the cleanup code with whatever fix is needed

cc @JackQuincy

**Comment by julienstroheker** [comment]
looking at it

**Comment by kwoodson** [comment]
@julienstroheker Did your fix in #247 solve this issue?

**Comment by jim-minter** [comment]
There remain multiple places where we need to audit and add `set -e`.

**Comment by jim-minter** [comment]
run_e2e is guarded by set -e, closing
