### ISSUE TITLE
Some create failure types make deleting the cluster impossible

### ISSUE THREAD

**Issue by JackQuincy** [Azure/ARO-RP#256]
If some cluster elements are missing (never created or deleted in previous failed delete attempt or deleted by customer) deletion will fail and not clean all resources/delete cluster from DB.  And the clusters will not be able to be deleted by any means available to the customer.

**Comment by jim-minter** [comment]
please can you give an example?

**Comment by JackQuincy** [comment]
If the entire Resource group is missing, due to customer deleting or it never being created. Then The call to delete the resource group will return an error [here](https://github.com/Azure/ARO-RP/blob/master/pkg/backend/openshiftcluster/delete.go#L89 ). which will cause this[ if statement ](https://github.com/Azure/ARO-RP/blob/master/pkg/backend/openshiftcluster.go#L138)to take the error case and the cluster to never to be deleted from the db. 
I'll email a link to example logs

**Comment by asalkeld** [comment]
it looks like you can't delete a healthy cluster's RG as it always leaves the pls, nsg, pip and lb
