### ISSUE TITLE
Precompiled extension 0.1.0 requires Azure CLI 2.0.67 to 2.1.0

### ISSUE THREAD

**Issue by lydodg** [Azure/ARO-RP#276]
following docs at https://docs.microsoft.com/en-us/azure/openshift/howto-using-azure-redhat-openshift

az extension add --source  https://arosvc.blob.core.windows.net/az-preview/aro-0.1.0-py2.py3-none-any.whl
Are you sure you want to install this extension? (y/n): y
The 'None' extension is not compatible with this version of the CLI.
You have CLI core version 2.2.0 and this extension requires a min of 2.0.67 and max of 2.1.0.
Please install a compatible extension version or remove it.

@jim-minter

**Comment by kwoodson** [comment]
@lydodg It appears this was updated 2 days ago here https://github.com/Azure/ARO-RP/blame/master/python/az/aro/azext_aro/azext_metadata.json.  Could you verify you are on the latest version?

**Comment by lydodg** [comment]
ah - i'm not compiling the extension, i'm using the precompiled that we reference in the (now public) docs at the top link in the issue. if we can update that precompiled, i can submit the pr to update the public doc to the new precompiled version.

**Comment by sabbour** [comment]
@kwoodson can the CI/CD process build and publish the extension into a well known URL? Or publish as a release on GitHub that people can go and grab the latest version?

**Comment by lydodg** [comment]
This would be a great thing to do - leverage the github actions in the repo to build/put into a releases section.

**Comment by jim-minter** [comment]
MSFT doesn't allow publishing to github releases.  I'll build and publish an updated az extension, it'll need a doc update to point to the new location though.

**Comment by sabbour** [comment]
@jim-minter can we publish to 2 URLs, a version specific one and an evergreen one, for example https://arosvc.blob.core.windows.net/az-preview/aro-latest-py2.py3-none-any.whl
This way we don't need to update docs everytime.

**Comment by jim-minter** [comment]
The new command is: `az extension add -n aro --index https://az.aroapp.io/preview`

The following should hopefully work to update to the new version: `az extension update -n aro --index https://az.aroapp.io/preview`

**Comment by jim-minter** [comment]
@sabbour / @lydodg / @jimzim / @sakthi-vetrivel if one of you can get the documentation updated I'd be most grateful.

**Comment by jimzim** [comment]
@sakthi-vetrivel is updating it right now.  Thanks for the quick turn around!

**Comment by lydodg** [comment]
https://github.com/MicrosoftDocs/azure-docs/pull/50088 I already summited the pr


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
