### ISSUE TITLE
Upgrade "github.com/ugorji/go/codec" dependency to 1.29

### ISSUE THREAD

**Issue by niontive** [Azure/ARO-RP#2865]
In ARO billing, we use CosmosDB database client's [Next](https://github.com/Azure/ARO-RP/blob/4ed27bbbc2eb863ac21f3f9ea93273ab8b37b80e/pkg/database/cosmosdb/zz_generated_database.go#L129) method to list billing documents. After making the HTTP request, we [decode](https://github.com/Azure/ARO-RP/blob/4ed27bbbc2eb863ac21f3f9ea93273ab8b37b80e/pkg/database/cosmosdb/zz_generated_cosmosdb.go#L141) the response body using `github.com/ugorji/go/codec`.

We recently upgrade to Go 1.20, which breaks this decode call ([upstream issue](https://github.com/ugorji/go/issues/388)). Version 1.29 has the fix.

**Comment by hawkowl** [comment]
Not sure when we fixed this, but this is fixed now.
