### ISSUE TITLE
Add default cluster role binding to support Azure Files Dynamic PVCs

### ISSUE THREAD

**Issue by jasonrhunter** [Azure/ARO-RP#295]
Reference Jason De Lorme email to aos-azure and aro-talk Wed Mar 18 2020 for full details.

Would it be possible to implement this cluster role binding for system:serviceaccount:kube-system:persistent-volume-binder by default in ARO 4.3.

**Comment by jim-minter** [comment]
@jasonrhunter please can you provide more detail here?

**Comment by jasonrhunter** [comment]
From Jason's email: 

If you attempt to create a dynamic Azure Files PVC in ARO 4.3, you will encounter this issue, but there is a workaround.

> Warning ProvisioningFailed 10s (x2 over 15s) persistentvolume-controller Failed to provision volume with StorageClass "azurefile": Couldn't create secret secrets is forbidden: User "system:serviceaccount:kube-system:persistent-volume-binder" cannot create resource "secrets" in API group "" in the namespace "openshift"

The workaround is well documented by Red Hat here: https://docs.openshift.com/container-platform/4.3/storage/dynamic-provisioning.html#azure-file-definition_dynamic-provisioning

**Comment by jim-minter** [comment]
Upstream issue is https://github.com/kubernetes/kubernetes/issues/59543

**Comment by jim-minter** [comment]
Documentation tasks for @lamek.

**Comment by jim-minter** [comment]
closing as in doc tracking doc
