### ISSUE TITLE
Broken link to cloud.redhat.com in the web console

### ISSUE THREAD

**Issue by m1kola** [Azure/ARO-RP#298]
There is currently a broken link in the web console that points to cloud.redhat.com. After visiting the link, user gets an error message:

> Cluster 7cbbd648-9b42-4683-84e6-eb7c3749f197 was not found, it might have been deleted or you don't have permission to see it.

We need to decide what to do with this link.

![image](https://user-images.githubusercontent.com/509198/77096627-81031680-6a07-11ea-860b-bb2e89d83c0f.png)

**Comment by jim-minter** [comment]
Need an upstream commit to disable the label when azure branding is set.  The code in question is [here](https://github.com/openshift/console/blob/6cd4ee3b994116b4c7f11c6d1c3f03d6330970af/frontend/public/components/cluster-settings/cluster-settings.tsx#L277-L282).

Need to get the fix backported to release-4.3.

**Comment by nilsanderselde** [comment]
https://github.com/openshift/console/pull/4837

**Comment by nilsanderselde** [comment]
Didn't notice @sjkingo was assigned, my bad.

**Comment by nilsanderselde** [comment]
I found two other locations where changes needed to be made and fixed it there, too.

[Commit from Nov 13, 2019 that hid "OpenShift Cluster Manager" if branding is `okd`](https://github.com/openshift/console/commit/e014e17566b838625b6f466e26ae9c915a699edd)

[New PR which builds on that to also hide it if branding is `azure`](https://github.com/openshift/console/pull/4837/files)

**Comment by nilsanderselde** [comment]
Fixed in:
- https://github.com/openshift/console/pull/4837 (4.5)
- https://github.com/openshift/console/pull/4956 (4.4)
- https://github.com/openshift/console/pull/4957 (4.3)

**Comment by nilsanderselde** [comment]
Will close once the 4.3.z backport makes it into a release

**Comment by nilsanderselde** [comment]
Released: https://access.redhat.com/errata/RHBA-2020:1529
