### ISSUE TITLE
Move from `dep` to Go modules

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#3]
https://github.com/jim-minter/rp/issues/4

**Comment by jim-minter** [comment]
Currently blocked because https://github.com/openshift/installer's nested vendor directories break `go mod`.

**Comment by mjudeikis** [comment]
main repositories are moving to right direction too:
https://github.com/openshift/api/issues/456

**Comment by mjudeikis** [comment]
https://github.com/openshift/installer/pull/2745 
This would enable ARO to use go modules

**Comment by olga-mir** [comment]
what would be the next step for this issue? The https://github.com/openshift/installer/pull/2745 PR has been merged. Since we are using installer fork: https://github.com/jim-minter/installer/tree/release-4.3-azure I'm assuming we should cherry-picking that commit into that fork?
