### ISSUE TITLE
unknown file type gpgme_off_t for older versions of gpgme 

### ISSUE THREAD

**Issue by gburges** [Azure/ARO-RP#301]
# github.com/Azure/ARO-RP/vendor/github.com/mtrmac/gpgme
vendor/github.com/mtrmac/gpgme/data.go:187:12: could not determine kind of name for C.gogpgme_data_seek
vendor/github.com/mtrmac/gpgme/data.go:53:53: could not determine kind of name for C.gpgme_off_t
cgo: 
gcc errors for preamble:
In file included from vendor/github.com/mtrmac/gpgme/data.go:6:0:
./go_gpgme.h:15:1: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
 ^
./go_gpgme.h:15:55: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
                                                       ^

Using latest packages available in RHEL7

https://github.com/proglottis/gpgme/issues/24

**Comment by jim-minter** [comment]
Won't fix.  Upgrade your development OS.

**Comment by jim-minter** [comment]
Well, maybe we might fix.  Setting the following environment variable helps: `CGO_CFLAGS="-Dgpgme_off_t=off_t"`

**Comment by mjudeikis** [comment]
:tada:

**Comment by troy0820** [comment]
Weird, that flag crashes (since added to the Makefile) my dev environment (OSX). I removed (commented it out) it from the makefile to run make test-go and it started working again.
