### ISSUE TITLE
Deployment template keyvalut prefix limited to 20 characters

### ISSUE THREAD

**Issue by sjkingo** [Azure/ARO-RP#317]
Attempting to [re-deploy the shared](https://github.com/Azure/ARO-RP/blob/master/hack/devtools/deploy-shared-env.sh#L18) v4-australiasoutheast resource group on Azure causes the following error as the prefix is limited to 20 characters, yet `v4-australiasoutheast` is 21 characters.

```
########## Deploying rp-development-predeploy in RG v4-australiasoutheast ##########
Azure Error: InvalidTemplate
Message: Deployment template validation failed: 'The provided value for the template parameter 'keyvaultPrefix' at line '1' and column '300' is not valid. Length of the value should be less than or equal to '20'. Please see https://aka.ms/arm-template/#parameters for usage details.'.
Additional Information:
	Type: TemplateViolation
	Info: {
	    "lineNumber": 1,
	    "linePosition": 300,
	    "path": "properties.template.parameters.keyvaultPrefix.maxLength"
	}
```

Where:

`KEYVALUT_PREFIX=v4-australiasoutheast`

@mjudeikis

**Comment by jim-minter** [comment]
If redeploying (why?) you should be using `KEYVAULT_PREFIX=v4-australiase`.
