### ISSUE TITLE
Production cleanups

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#325]
Laundry list of config changes that need to be cleaned in production
- we used to edit the privileged scc for cluster logging, now we create a new one.  Remove our change to the privileged scc (otherwise in future the cluster will be marked unupgradable) and create the new one
- we added the system:aro-service user (will need to find the graph again to make this)
- geneva logging daemonset config changed
- alertmanager hack
- added record to billing table (cross-check with @julienstroheker on this one)
- deny assignments

**Comment by jim-minter** [comment]
@mjudeikis ^ is a list of some things that will be stale on some prod clusters.  Surely there are items missing from this list - can you see what else?  Please can you look at a way in which, when we do an admin PUT, we can check and remediate these issues on a production cluster?

There are two sides to this.  1- let's try and get all the clusters on a level in the short term. 2- we need to lay foundations for a smarter approach in future.

**Comment by mjudeikis** [comment]
This needs a little bit more flushing. 
Currently, we do "AdminPost" for Cluster upgrades.
Do we want to add "AdminPut" for infrastructure related things, or we want to do this as part of "AdminPost"?
