### ISSUE TITLE
Add python az tests

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#368]
`make test-python` is broken. 

This needs fixing for az binary.

In addition change validation rules:
```
ou can add type=int to require the parameter value is an integer and must be greater than or equal to 128 such
that could save the work of validate function _validate_int
```
https://github.com/Azure/azure-cli/pull/12793/files#r401333891

**Comment by sjkingo** [comment]
The tests appear to work OK.

I have replaced the custom `_validate_int` function with `type=int` as supported on argparse.
