### ISSUE TITLE
invalid configuration in enrichOne

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#389]
Saw the following RP error in eastus2 (you can check Jarvis if needed):
"invalid configuration: no configuration has been provided" at clusterdata.go:71

I think we got an incoming GET on the cluster when it was being created, before the kubeadmin was in place.

I think the fix is that enrichment should not take place if the cluster is in state Creating or Failed/Creating, probably not Deleting or Failed/Deleting as well.

**Comment by JackQuincy** [comment]
I ran an e2e and didn't define the parameters e2e needs to sign in and download the kube config.  That could of been it

**Comment by JackQuincy** [comment]
never mind me. It seems all creates are failing and it wasn't a problem with just my run
