### ISSUE TITLE
InstallPhaseDeployResources is not restartable any more

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#398]
Since 0aa3b6682840e50f98689f740d75ddce9fb7fae7, InstallPhaseDeployResources is not restartable any more.

If the RP crashes in InstallPhaseDeployResources after successfully deploying the deployment template, it generates an persists a new graph, then tries to redeploy the deployment template.  All 4 VMs then get a deployment error of 

```
{
    "error": {
        "code": "PropertyChangeNotAllowed",
        "message": "Changing property 'customData' is not allowed.",
        "target": "customData"
    }
}
```

The master VMs get this error straightforwardly because the graph crypto has changed.
I think the bootstrap VM gets this error because Install.Now changes when it shouldn't.

@nilsanderselde please prioritise resolving this.

**Comment by nilsanderselde** [comment]
@jim-minter I'm about to test this possible fix: https://github.com/nilsanderselde/ARO-RP/commit/0138d8a713932b71d1153a5a5186c820503d6ee6
