### ISSUE TITLE
service_principal_task should not touch tenantID

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#401]
tenantID is an internal field, there is no reason for service_principal_task to do anything with it.  Should be fixed now before it gets confusing.

**Comment by m1kola** [comment]
@jim-minter we return `tenantId` in admin API. What if a customer changed cloud provider config and set new `tenantId` and `clientId`? In the admin API we will be returning the new `clientId`, but a stale `tenantId`?

**Comment by jim-minter** [comment]
That is a very good reason to leave things as they are, hehe.  Thanks.
