### ISSUE TITLE
Unit tests for validation on !isCreate

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#413]
Follow-up from #404.

On a non-creating PUT, we don't currently test that:
* we don't care about the contents of WorkerProfiles or Version (as long as they don't change).
* we do care about the contents of every other field.

i.e. the `if isCreate`s added in #404 don't have test coverage, and I think they should.

**Comment by m1kola** [comment]
I think there is a wider issue with tests for validator. We do have some tests for cases mentioned above in `TestOpenShiftClusterStaticValidateDelta`, but It seems like all other tests only test create path.

We should be able to improve it by adding `runTests(t, tests, true)` along `runTests(t, tests, false)` into most of the tests. Some tests will require additional create and update -specific test cases.
