### ISSUE TITLE
OAuth nickname as display name instead of familiy_name 

### ISSUE THREAD

**Issue by bentterp** [Azure/ARO-RP#458]
Hi,
is it possible somehow to use the Azure AD optional clame of nickname as the display name instead of family name?

I've messed around som and tried but can't get it working.

The reason behind this is that upn looks not very nice, but we simply have way too many Nilssons in our company....

//Bent

**Comment by jim-minter** [comment]
Hi!  Not in v3 without a feature request.  In v4 you have control over this integration and I think it should be doable - see https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-oidc-identity-provider.html#configuring-oidc-identity-provider

**Comment by bentterp** [comment]
With the GA it defaults to Firstname Lastname now, so that's good enough. Thanks
