### ISSUE TITLE
c# serialisation bug

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#525]
I don't have all the details, but when running a k8s createorupdate to update an object, I think I posted
```yaml
...
metadata:
  generation: 2
...
```

and I got some error back from k8s that makes me think that the yaml->json c# incorrectly serialised that to `"metadata": {"generation": "2"}` (i.e. "2" as a string, not a number).

are you able to recreate this?

**Comment by jim-minter** [comment]
c# is serialising both ints and bools to strings when converting yaml to json - this blocks creating/updating a lot of k8s objects.  @asalkeld please investigate as a priority.

**Comment by asalkeld** [comment]
PR here https://msazure.visualstudio.com/One/_git/Compute-ARO-GenevaActions/pullrequest/2871614
