### ISSUE TITLE
can't deploy in southeastasia

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#526]
We're currently blocked rolling out the southeastasia RP.  When the RP VMs boot, we get the following repeatable error:

> [stdout]
> Red Hat Enterprise Linux 8 for x86_64 - BaseOS   47 MB/s |  15 MB     00:00    
> Red Hat Enterprise Linux 8 for x86_64 - AppStre  48 MB/s |  15 MB     00:00    
> Red Hat CodeReady Linux Builder for RHEL 8 x86_  12 MB/s | 2.9 MB     00:00    
> Microsoft Azure RPMs for Red Hat Enterprise Lin  24 kB/s | 1.4 kB     00:00    
> (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> 
> [stderr]
> ++ yum -y update -x WALinuxAgent
> Error: 
>  Problem: The operation would result in removing the following protected packages: systemd

**Comment by gburges** [comment]
https://github.com/Azure/ARO-RP/pull/534
