### ISSUE TITLE
Simplify our frontend unit tests

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#546]
Too many arguments to NewFrontend.  Need to find a better way.

**Comment by sjkingo** [comment]
The best way to do this is to remove the test-only arguments from `NewFrontend`, which makes the new signature of minimally required arguments:

```
func NewFrontend(ctx context.Context, baseLog *logrus.Entry, _env env.Interface, db *database.Database, m metrics.Interface, cipher encryption.Cipher) (Runnable, error)
```

The test-only arguments can then be provided in the tests in one of two ways:

1. Create a new wrapper `newFrontendForTest` that takes the original amount of arguments. This will simply shift the issue from `frontend/frontend.go` to `frontend/frontend_test.go`. Not ideal if this issue remains as-is.

2. Create an enrich function in the tests that takes a `frontend` instance (from the shortened `NewFrontend`, above) and the test-only arguments and sets those fields in the struct. This issue would then be better named "don't pass test-only arguments to `NewFrontend`".

I'm leaning towards the second, even though it will result in more code.

I'll put up a PR for each and see what everyone thinks.

**Comment by mjudeikis** [comment]
I think we need to investigate what can be initiated inside the function. If this will not save us enough, we can create `frontendOpt` struct as part of Frontend pkg and pass all the same values as one struct.

**Comment by jim-minter** [comment]
I don't really think that either of these options is worth the churn.  We know we have so much boilerplate in the frontend tests and they are hard to understand and debug.  Working to reduce the boilerplate, and hence probably the number of calls to NewFrontend, and improve the legibility, is the first step here.
