### ISSUE TITLE
Tools to debug create reliability problems

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#560]
Seeing a few create timeouts - check Jarvis.  What tooling do we need to further debug?

Probably need to gather and log specifics when we get install timeout errors.  Not sure what specifics.

**Comment by jim-minter** [comment]
We are getting stuck on operatorConsoleExists a lot.  Need logging.

**Comment by jim-minter** [comment]
search for pkg/backend/openshiftcluster.go:196 in prod logs

**Comment by mjudeikis** [comment]
I was checking this, but I think its too big of attach surface.

What if we add "heper method to our RP:
```
err := i.Install(ctx, installConfig, platformCreds, image)
if err!=nil{
   i.GatherFailureLogs(ctx, installConfig)
}
```

If we faield after API server is alive, I think we can gather most of the required data from the cluster. Like Operator statuses, etc and log them out?
