### ISSUE TITLE
Migrate existing cluster LBs to use /readyz

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#617]
See #616

**Comment by mjudeikis** [comment]
@jim-minter should we start constructing concepts to do infrastructure changes in our code during upgrades? `InfrastructureUpgrade` api call in example?

**Comment by asalkeld** [comment]
merged here https://github.com/Azure/ARO-RP/pull/654/commits/f64d4abeb834f964d9943a0bdc9e6f9e7cec34b7
