### ISSUE TITLE
[azure-cli] CLI documentation missing

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#699]
* Valid values need to be documented in the CLI. 
* Pod & Service CIDR must be /18 or larger

issue: https://github.com/Azure/azure-cli/issues/13530 
issues 2 https://github.com/Azure/azure-cli/issues/13531

**Comment by mjudeikis** [comment]
Needs to merge first: https://github.com/Azure/ARO-RP/pull/663

**Comment by troy0820** [comment]
PR https://github.com/Azure/azure-cli/pull/13550/ to add params Private/Public to ingress/apiserver visiblity.

**Comment by mjudeikis** [comment]
Do we have this in our Repo already?

**Comment by troy0820** [comment]
This is not in our repo yet.  I will synchronize the changes necessary and start here before any changes are made downstream.

**Comment by m1kola** [comment]
Had a question from the field about master subnet. Our docs [1] [2] suggest to use `/23`, but "`/27` or larger" master and worker subnets are actually allowed.

[1] https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster
[2] https://docs.microsoft.com/en-us/azure/openshift/create-private-cluster

**Comment by mjudeikis** [comment]
@m1kola what is your question here?

**Comment by m1kola** [comment]
@mjudeikis sorry, I should have included the original question in my previous comment:

> In the ARO documentation the master subnet is a /23. Is this needed? Seems big for running 3 masters.

So it's not clear to people what is a minimum size of the subnet from the docs and CLI.
