### ISSUE TITLE
Move code generation comments into separate files

### ISSUE THREAD

**Issue by m1kola** [Azure/ARO-RP#71]
Would be nice to have code generation-related comments in separate files (eg `generate.go` in a package): it makes clear that the package has something to do with go generate and where to make modifications to code generation. Some packages already have this file. Some packages need to be updated.

As an extra excercise, we can write a small tool to enforce this in CI (see `go/ast`/`go/parser` packages for references).

See https://github.com/Azure/ARO-RP/pull/69#discussion_r366323293 for the background.

**Comment by jim-minter** [comment]
assigning on behalf of @sjkingo
