### ISSUE TITLE
Get rid of hardcoded values in codebase

### ISSUE THREAD

**Issue by m1kola** [Azure/ARO-RP#72]
We've got NSG names hardcoded [in `subnet`](https://github.com/Azure/ARO-RP/blob/9f98531cd80248eeb7e6813704bb078eef319479/pkg/util/subnet/subnet.go#L79-L90) and [in `installer`](https://github.com/Azure/ARO-RP/blob/14918d66314e1698578d4cc082ad47e6fbf400ed/pkg/install/0-installstorage.go#L161-L169) packages. Our current tests will not detect the fact that we updated it in one place and failed to do so in other places.

Should review existing codebase and replace values like this with constants and\or add tests to cover this.

Background: https://github.com/Azure/ARO-RP/pull/69#discussion_r366333065

**Comment by jim-minter** [comment]
assigning on behalf of @sjkingo

**Comment by sjkingo** [comment]
Closed in #514
