### ISSUE TITLE
Can not delete a cluster with stopped VMs

### ISSUE THREAD

**Issue by m1kola** [Azure/ARO-RP#721]
Related to https://github.com/Azure/ARO-RP/issues/687

There are several flavours of this issue. We currently can not recover from cases 1 & 2.

1. When a cluster in failed state from where we can not run admin update. For example `provisioningState=Failed` and `failedProvisioningState=Deleting` ([ref](https://github.com/Azure/ARO-RP/blob/64a15e5b607bb6d77f666ab88a088994262e8197/pkg/frontend/openshiftcluster_putorpatch.go#L96-L108)).
1.  When a cluster is in succeded state, but VMs are stopped + we *can not* start them (in a suspended subscription, for example)
1.  When a cluster is in succeded state, but VMs are stopped + we *can* start them (cluster was in suspended subscription, but it's no longer a case) - should be possible to recover and delete once we have a proper fix for https://github.com/Azure/ARO-RP/issues/687

RP panics with `runtime error: index out of range [0] with length 0` here on line 30 (see full panic at the end).

https://github.com/Azure/ARO-RP/blob/64a15e5b607bb6d77f666ab88a088994262e8197/pkg/backend/openshiftcluster/delete.go#L28-L31

This happens because worker profile is a dynamic data which we receive from cluster's API server. When we can not reach the API server worker profile is not populated (`nil`).

---

```
pkg/util/recover/recover.go:19 recover.Panic() goroutine 314 [running]:
runtime/debug.Stack(0xc00042d110, 0x2, 0xc0006d1a08)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/Azure/ARO-RP/pkg/util/recover.Panic(0xc00042d110)
	/Users/mradchuk/workspace/src/github.com/Azure/ARO-RP/pkg/util/recover/recover.go:19 +0x9a
panic(0x65b1d80, 0xc000c73480)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.(*Manager).Delete(0xc002f7e300, 0x6d29f20, 0xc000c6e800, 0x1, 0x1)
	/Users/mradchuk/workspace/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster/delete.go:30 +0xd20
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).handle(0xc000118288, 0x6d29f60, 0xc0000d6000, 0xc00042d110, 0xc000400300, 0x0, 0x0)
	/Users/mradchuk/workspace/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:126 +0x33d
github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try.func1(0xc00042d110, 0xc000118288, 0xc000400300)
	/Users/mradchuk/workspace/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:62 +0x121
created by github.com/Azure/ARO-RP/pkg/backend.(*openShiftClusterBackend).try
	/Users/mradchuk/workspace/src/github.com/Azure/ARO-RP/pkg/backend/openshiftcluster.go:49 +0x309
```

**Comment by jim-minter** [comment]
I don't think we don't call Enrich() on the backend currently?  What are the circumstances in which WorkerProfiles does not have length 1?

Possibly the logic here should walk the NSGs in the managed RG and make sure they are detached from any subnets so they can then be deleted.

**Comment by m1kola** [comment]
@jim-minter hm, right we do not call `Enrich()` on backend. But in my db (RH subscription, `v4-eastus` RG) I somehow ended up with a document which does not have worker profiles. Wondering if there is a bug somewhere in front-end where we call Enrich and save the enriched document in DB... Need to try this:

1. Create a cluster
1. Stop VMs
1. Make sure that DB document has worker profiles field
1. Try to send an admin udpate (patch) request while VMs are powered off
1. Check DB

I'll try to reproduce it tomorrow.

**Comment by m1kola** [comment]
My suspec is this bit:

https://github.com/Azure/ARO-RP/blob/64a15e5b607bb6d77f666ab88a088994262e8197/pkg/frontend/openshiftcluster_putorpatch.go#L110-L114

And below we have:

https://github.com/Azure/ARO-RP/blob/64a15e5b607bb6d77f666ab88a088994262e8197/pkg/frontend/openshiftcluster_putorpatch.go#L203

**Comment by jim-minter** [comment]
Makes sense.  In that case I think the delete code should iterate NSGs.

**Comment by jim-minter** [comment]
I agree on the priority.
