### ISSUE TITLE
Failing python unit tests for multiple resource group parameters on aro extensions.

### ISSUE THREAD

**Issue by petrkotas** [Azure/ARO-RP#766]
The unit tests for python started to fail on the following error.

```
FAIL - HIGH severity: parameter_should_not_end_in_resource_group
    Parameter: aro create, `cluster_resource_group` - A command should only have '--resource-group' as its resource group parameter. However options '--cluster-resource-group' in command 'aro create' end with 'resource-group' or similar.
    Parameter: aro create, `vnet_resource_group_name` - A command should only have '--resource-group' as its resource group parameter. However options '--vnet-resource-group' in command 'aro create' end with 'resource-group' or similar.

```

The failure is at least in the following prs:
* https://github.com/Azure/ARO-RP/pull/763
* https://github.com/Azure/ARO-RP/pull/693

Renaming should be an option.

**Comment by jim-minter** [comment]
see https://github.com/Azure/azure-cli/blob/5fe403f21d44a839eec1f358702076998bbc2f38/linter_exclusions.yml#L64-L71

**Comment by jim-minter** [comment]
we need to set up a linter_exclusions file too, I guess?

**Comment by kwoodson** [comment]
@jim-minter @petrkotas 
Is this the linter exclusion file that is missing? https://github.com/Azure/ARO-RP/pull/693/files#diff-0bd0f4acbef9aa1d479ae24c9f3232ca
