### ISSUE TITLE
mdsd secret hash to ensure cert rotation

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#788]
include a hash of the cluster mdsd secret in the mdsd pod so that if the certificate rotates, the pods will also rotate.  We did this in 3.11, need to copy it to 4.x

@asalkeld fyi

**Comment by asalkeld** [comment]
this is done here now: https://github.com/Azure/ARO-RP/blob/master/pkg/operator/controllers/genevalogging/genevalogging_controller.go#L99
