### ISSUE TITLE
cosmosdb load test

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#94]
cosmosdb package is doing exponential requests backoff when RU's are exceeded.

We need to have reproducible for load testing so we could be sure that if RU's are exceeded cosmos client will retry until load is evenly distributed

**Comment by m1kola** [comment]
Setting medium priority and large size to this (we don't have anything for load testing, at the moment).

Please correct the labels, if you think differently.

**Comment by jim-minter** [comment]
Moved to VSTS
