### ISSUE TITLE
Fix RP vendoring

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#940]
Our version of CVO does not have all required status fields:
```
const OperatorFailing configv1.ClusterStatusConditionType = "Failing"

//TODO: this is duplicate from clusterversioncondition.go
var clusterVersionConditionsHealthy = map[configv1.ClusterStatusConditionType]configv1.ConditionStatus{
	configv1.OperatorAvailable:   configv1.ConditionTrue,
	configv1.OperatorProgressing: configv1.ConditionFalse,
	configv1.OperatorDegraded:    configv1.ConditionFalse,
	configv1.OperatorUpgradeable: configv1.ConditionTrue,
	Op

```
https://github.com/Azure/ARO-RP/blob/76c3cd4889ead6a31ad7e6e1b11d4c8313930a64/pkg/util/status/clusterversionoperator_status.go#L10-L19
Investigate and potentially bump vendoring

**Comment by petrkotas** [comment]
It seems that the issue is related to the openshift/cluster-version-operator. Created the issue https://github.com/openshift/cluster-version-operator/issues/437

**Comment by petrkotas** [comment]
Added PR explaining the issue to the code. https://github.com/Azure/ARO-RP/pull/945
