### ISSUE TITLE
  Can run a pod which is using Azure File storage flake

### ISSUE THREAD

**Issue by jim-minter** [Azure/ARO-RP#970]
```
• Failure [141.320 seconds]
Cluster smoke test
/data/vsts-agent/_work/13/s/gopath/src/github.com/Azure/ARO-RP/test/e2e/cluster.go:29
  Can run a pod which is using Azure File storage [It]
  /data/vsts-agent/_work/13/s/gopath/src/github.com/Azure/ARO-RP/test/e2e/cluster.go:51

  Timed out after 120.001s.
  Expected
      <*errors.StatusError | 0xc00036a280>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "pods \"busybox\" not found",
              Reason: "NotFound",
              Details: {Name: "busybox", Group: "", Kind: "pods", UID: "", Causes: nil, RetryAfterSeconds: 0},
              Code: 404,
          },
      }
  to be nil

  /data/vsts-agent/_work/13/s/gopath/src/github.com/Azure/ARO-RP/test/e2e/cluster.go:61
```

https://msazure.visualstudio.com/AzureRedHatOpenShift/_build/results?buildId=34571489&view=logs&j=10f66467-59e5-53bc-0c8a-42cc89770de4&t=f00aaa95-0643-5e60-2886-48bbeb9c10f0

**Comment by jim-minter** [comment]
@olga-mir ptal at this.  Also, the name "Can run a pod which is using Azure File storage" is misleading - this is an azure disk test, not an azure file test.  Please can you fix that up too?

**Comment by olga-mir** [comment]
I have fixed the test name. 
As for the failure itself I am think this is because it is the first test and runs right after the cluster is created:
```
2020-09-07T18:47:38.8137650Z - cluster creation finished
2020-09-07T18:47:43.7288982Z - test start
```
I wasn't able to reproduce locally with the same seed, but I was running on existing cluster

**Comment by olga-mir** [comment]
I have run multiple attempts of cluster creation immediately followed by e2e test with this test seed. I was not able to reproduce this issue.
