### ISSUE TITLE
pause on BBM ImagePruningDisabled alert

### ISSUE THREAD

**Issue by mjudeikis** [Azure/ARO-RP#976]
Currently, ALL clusters are firing `ImagePruningDisabled`
It was a miss-use by upstream to use alert for user notifications. 
https://github.com/openshift/origin/pull/24901

We need to enable this on our cluster as it is the default for 4.5

**Comment by jim-minter** [comment]
I think we need to do things:
* we can enable pruning by default on 4.5
* we should ignore the warning in BBM as it's not really in our remit to fix

**Comment by mjudeikis** [comment]
| we can enable pruning by default on 4.5

It is already enabled

| we should ignore the warning in BBM as it's not really in our remit to fix 

ACK
